package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

/**
 * AdminAccount generated by hbm2java
 */
public class AdminAccount implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String username;
	private String password;
	private String dob;
	private String emailId;
	private String phoneNo;

	public AdminAccount() {
	}

	public AdminAccount(String firstName, String lastName, String username, String password, String dob, String emailId,
			String phoneNo) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.dob = dob;
		this.emailId = emailId;
		this.phoneNo = phoneNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

}
