package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

/**
 * CardDetails generated by hbm2java
 */
public class CardDetails implements java.io.Serializable {

	private Integer id;
	private UserAccount userAccount;
	private String cardType;
	private String cardNo;
	private String nameOnCard;
	private String cvc;
	private String expiryDate;

	public CardDetails() {
	}

	public CardDetails(UserAccount userAccount, String cardType, String cardNo, String nameOnCard, String cvc,
			String expiryDate) {
		this.userAccount = userAccount;
		this.cardType = cardType;
		this.cardNo = cardNo;
		this.nameOnCard = nameOnCard;
		this.cvc = cvc;
		this.expiryDate = expiryDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	public String getCvc() {
		return this.cvc;
	}

	public void setCvc(String cvc) {
		this.cvc = cvc;
	}

	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

}
