package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private UserAccount userAccount;
	private String status;
	private Integer amount;
	private String comment;

	public Cart() {
	}

	public Cart(Projects projects, UserAccount userAccount, String status, Integer amount, String comment) {
		this.projects = projects;
		this.userAccount = userAccount;
		this.status = status;
		this.amount = amount;
		this.comment = comment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
