package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private Integer id;
	private String categoryName;
	private String description;
	private String status;
	private byte[] image;
	private Set<Projects> projectses = new HashSet<Projects>(0);

	public Categories() {
	}

	public Categories(String categoryName, String description, String status, byte[] image, Set<Projects> projectses) {
		this.categoryName = categoryName;
		this.description = description;
		this.status = status;
		this.image = image;
		this.projectses = projectses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

}
