package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private UserAccount userAccount;
	private String amount;
	private String dateOfPayment;
	private String comment;

	public Donation() {
	}

	public Donation(Projects projects, UserAccount userAccount, String amount, String dateOfPayment, String comment) {
		this.projects = projects;
		this.userAccount = userAccount;
		this.amount = amount;
		this.dateOfPayment = dateOfPayment;
		this.comment = comment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getDateOfPayment() {
		return this.dateOfPayment;
	}

	public void setDateOfPayment(String dateOfPayment) {
		this.dateOfPayment = dateOfPayment;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
