package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects implements java.io.Serializable {

	private Integer id;
	private Categories categories;
	private UserAccount userAccount;
	private String createdOn;
	private String projectName;
	private String description;
	private String amontRequired;
	private String amountRecieved;
	private String deadline;
	private String status;
	private Integer donationCount;
	private Set<Donation> donations = new HashSet<Donation>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);

	public Projects() {
	}

	public Projects(Categories categories, UserAccount userAccount, String createdOn, String projectName,
			String description, String amontRequired, String amountRecieved, String deadline, String status,
			Integer donationCount, Set<Donation> donations, Set<Cart> carts) {
		this.categories = categories;
		this.userAccount = userAccount;
		this.createdOn = createdOn;
		this.projectName = projectName;
		this.description = description;
		this.amontRequired = amontRequired;
		this.amountRecieved = amountRecieved;
		this.deadline = deadline;
		this.status = status;
		this.donationCount = donationCount;
		this.donations = donations;
		this.carts = carts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAmontRequired() {
		return this.amontRequired;
	}

	public void setAmontRequired(String amontRequired) {
		this.amontRequired = amontRequired;
	}

	public String getAmountRecieved() {
		return this.amountRecieved;
	}

	public void setAmountRecieved(String amountRecieved) {
		this.amountRecieved = amountRecieved;
	}

	public String getDeadline() {
		return this.deadline;
	}

	public void setDeadline(String deadline) {
		this.deadline = deadline;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getDonationCount() {
		return this.donationCount;
	}

	public void setDonationCount(Integer donationCount) {
		this.donationCount = donationCount;
	}

	public Set<Donation> getDonations() {
		return this.donations;
	}

	public void setDonations(Set<Donation> donations) {
		this.donations = donations;
	}

	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

}
