package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private Integer id;
	private String country;
	private Integer count;

	public Report() {
	}

	public Report(String country, Integer count) {
		this.country = country;
		this.count = count;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
