package neu.edu.entity;
// Generated 23 Apr, 2017 2:44:42 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String username;
	private String password;
	private String dob;
	private String country;
	private String emailId;
	private String phoneNo;
	private String role;
	private Set<Projects> projectses = new HashSet<Projects>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<CardDetails> cardDetailses = new HashSet<CardDetails>(0);
	private Set<Donation> donations = new HashSet<Donation>(0);

	public UserAccount() {
	}

	public UserAccount(String firstName, String lastName, String username, String password, String dob, String country,
			String emailId, String phoneNo, String role, Set<Projects> projectses, Set<Cart> carts,
			Set<CardDetails> cardDetailses, Set<Donation> donations) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.dob = dob;
		this.country = country;
		this.emailId = emailId;
		this.phoneNo = phoneNo;
		this.role = role;
		this.projectses = projectses;
		this.carts = carts;
		this.cardDetailses = cardDetailses;
		this.donations = donations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	public Set<CardDetails> getCardDetailses() {
		return this.cardDetailses;
	}

	public void setCardDetailses(Set<CardDetails> cardDetailses) {
		this.cardDetailses = cardDetailses;
	}

	public Set<Donation> getDonations() {
		return this.donations;
	}

	public void setDonations(Set<Donation> donations) {
		this.donations = donations;
	}

}
